name: push action

on:
  schedule:
    - cron: '0 0 * * *' # Everyday At 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing repo
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute python script # run main.py
        run: python myLifetime.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -am "daily update" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
