name: !!str Test

on: !!str workflow_dispatch
 
jobs: !!map
  generate: !!map
    runs-on: !!str ubuntu-latest
    env: !!map
      MIN_SLEEP: !!str ${{ secrets.MIN_SLEEP }}
      MAX_SLEEP: !!str ${{ secrets.MAX_SLEEP }}
      MONTH: !!str ${{ secrets.MONTH }}
      UNIXTIME: !!str ${{ secrets.UNIXTIME }}
    
    steps: !!seq
      - name: !!str Initializing repo
        uses: !!str actions/checkout@v3 # checkout the repository content to github runner

      - name: !!str Setup python
        uses: !!str actions/setup-python@v4

      - name: !!str Execute python script 
        run: !!str python daily_generator.py $MIN_SLEEP $MAX_SLEEP $MONTH -u $UNIXTIME

      - name: !!str Show results
        run: !!str sed -n "12,20p" README.md

      - name: !!str Check README
        run: !!str cat README.md
